[package]
name = "hipptrack"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.73"
crc = "3.2.1"
hashbrown = "0.14.5"
itertools = "0.13.0"
rusqlite = "0.31.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
